# Definimos la función para eliminar duplicados de la lista de canciones
def remove_duplicates(songs):
    seen = set()
    cleaned_songs = []

    for song in songs:
        # Normalizamos la cadena para evitar problemas con mayúsculas y espacios
        normalized_song = song.strip().lower()
        if normalized_song not in seen:
            seen.add(normalized_song)
            cleaned_songs.append(song)  # Agregamos la canción original a la lista limpia
        else:
            print(f"Duplicado encontrado y eliminado: {song}")

    return cleaned_songs

# Lista de canciones proporcionada por el usuario (sin duplicados)
song_list = [
    "La Bilirrubina - Juan Luis Guerra",
    "Oye Cómo Va - Tito Puente",
    "Vivir Mi Vida - Marc Anthony",
    "Bamboleo - Gipsy Kings",
    "Aventura - Obsesión",
    "La Vida Es Un Carnaval - Celia Cruz",
    "Bailar Contigo - La Sonora Dinamita",
    "Te Amo - Franco de Vita",
    "Cali Pachanguero - Grupo Niche",
    "Quimbara - Celia Cruz",
    "Cumbia Cienaguera - Carlos Vives",
    "Mi Gente - J Balvin, Willy William",
    "La Gata - Rigo Tovar",
    "El Perdón - Nicky Jam ft. Enrique Iglesias",
    "La Cumbia De Los Pajaritos - Los Ángeles Azules",
    "La Cumbia De La Cadenita - Grupo Cañaveral",
    "Perdóname - La Sonora Santanera",
    "La Bamba - Los Lobos",
    "Danza Kuduro - Don Omar ft. Lucenzo",
    "Cumbia Sobre El Río - Celso Piña",
    "Limón y Sal - Julieta Venegas",
    "Te Quiero - Hombres G",
    "Cumbia De Los Abuelos - La Sonora Santanera",
    "No Hay Manera - Aventura",
    "La Gozadera - Gente de Zona ft. Marc Anthony",
    "Cerca Del Mar - Los Angeles Azules",
    "Moliendo Café - Hugo Blanco",
    "Chantaje - Shakira ft. Maluma",
    "Cielo - Benny Ibarra",
    "Bailando - Enrique Iglesias ft. Descemer Bueno, Gente de Zona",
    "Cuerpo Loco - Los Hermanos Rosario",
    "Cumbia y Tequila - Grupo Cañaveral",
    "Cuando Me Acaricias - Los Bukis",
    "Rayando El Sol - Maná",
    "Bachata Rosa - Juan Luis Guerra",
    "Quiero bailar contigo - Grupo Cañaveral",
    "Salta - La Sonora Dinamita",
    "Bachata en Fukuoka - Juan Luis Guerra",
    "Cumbia De Los Tristes - La Sonora Dinamita",
    "Déjala Que Vuelva - Piso 21 ft. Manuel Turizo",
    "Piel Canela - Bobby Capó",
    "Azúcar - Juanes",
    "La Chona - Los Tucanes de Tijuana",
    "En el muelle de San Blas - Maná",
    "Eres Tú - Mocedades",
    "Aventura - La Boda",
    "Que Te Vaya Bonito - José Alfredo Jiménez",
    "Copa tras copa - Grupo Cañaveral",
    "No Tengo Dinero - José José",
    "Colocao - Ozuna",
    "Baila Esta Cumbia - Selena",
    "Te Amo - Franco de Vita",
    "Ven Devórame Otra Vez - Lalo Rodríguez",
    "No hay nada más - Los Bukis",
    "Cielo - La Oreja de Van Gogh",
    "Soy Yo - Bomba Estéreo",
    "La negra tiene tumbao - Celia Cruz",
    "Te Quiero - Hombres G",
    "Cumbia En Do Mayor - Los Ángeles Azules",
    "La Cumbia Del Río - Los Ángeles Azules",
    "El Amor Es Un Pájaro - La Sonora Santanera",
    "Píntame - Los Ángeles Azules",
    "Ángelito - La Sonora Dinamita",
    "Como La Flor - Selena",
    "Sopa De Caracol - Banda Blanca",
    "Que Me Importa El Mundo - La Sonora Dinamita",
    "Enamorado de Ti - Los Ángeles Azules",
    "Baila Conmigo - Selena",
    "Sabrosura - El Gran Combo de Puerto Rico",
    "Dame Más - Grupo Cañaveral",
    "Ya No Hay Más - La Sonora Dinamita",
    "Te Amo - Franco de Vita",
    "Cielo - La Oreja de Van Gogh",
    "Cuando Te Vuelvas A Enamorar - Los Bukis",
    "La La La - Kiri",
    "Mujer - Los Tigres del Norte",
    "Sopa de Caracol - Banda Blanca",
    "Bailando - Enrique Iglesias ft. Descemer Bueno, Gente de Zona",
    "Taki Taki - DJ Snake",
    "La Cumbia De La Vida - Kumbia Kings",
    "El Perdón - Nicky Jam",
    "El Sol No Regresa - La Oreja de Van Gogh",
    "La Cumbia del Río - Grupo Cañaveral",
    "Bebé - Nicky Jam",
    "Despacito - Luis Fonsi ft. Daddy Yankee",
    "Deja Que Te Bese - Alejandro Sanz ft. Marc Anthony",
    "Eres Tú - Mocedades",
    "La Bamba - Los Lobos",
    "Vivir Mi Vida - Marc Anthony",
    "Aventura - Obsesión",
    "La Vida Es Un Carnaval - Celia Cruz",
    "Pena - Los Bukis",
    "Como La Flor - Selena",
    "A dónde Vamos A Parar - La Sonora Santanera",
    "Deja Que Te Bese - Alejandro Sanz ft. Marc Anthony",
    "En El Muelle De San Blas - Maná",
    "Caminando - Grupo Cañaveral",
    "Baila esta cumbia - Selena",
    "La Gata - Rigo Tovar",
    "La Cumbia De Los Pajaritos - Los Ángeles Azules",
    "Cumbia De Los Abuelos - La Sonora Santanera",
    "Todo Cambió - La Oreja de Van Gogh",
    "Cumbia En Do Mayor - Los Ángeles Azules",
    "Copa Tras Copa - Grupo Cañaveral",
    "Me Gusta - Anitta",
    "Vivir Mi Vida - Marc Anthony",
    "Eres Tú - Mocedades",
    "Baila Esta Cumbia - Selena",
    "Aventura - La Boda",
    "El Amor Es Un Pájaro - La Sonora Santanera",
    "Perdóname - La Sonora Santanera",
    "Como La Flor - Selena",
    "No hay nada más - Los Bukis",
    "Sopa De Caracol - Banda Blanca",
    "Ya No Hay Más - La Sonora Dinamita",
    "Mujer - Los Tigres del Norte",
    "La La La - Kiri",
    "La Bamba - Los Lobos",
    "Despacito - Luis Fonsi ft. Daddy Yankee",
    "La Cumbia De La Vida - Kumbia Kings",
    "Cielo - La Oreja de Van Gogh",
    "Te Amo - Franco de Vita",
    "Ven Devórame Otra Vez - Lalo Rodríguez",
    "Ya No Hay Más - La Sonora Dinamita",
    "Dame Más - Grupo Cañaveral",
    "Taki Taki - DJ Snake",
    "Sopa De Caracol - Banda Blanca",
    "La Gata - Rigo Tovar",
    "Como La Flor - Selena",
    "La Bamba - Los Lobos",
    "Deja Que Te Bese - Alejandro Sanz ft. Marc Anthony",
    "El Perdón - Nicky Jam",
    "Bebé - Nicky Jam",
    "Todo Cambió - La Oreja de Van Gogh"
]

# Llamar a la función y obtener la lista limpia
cleaned_song_list = remove_duplicates(song_list)

# Guardar la lista limpia en un archivo de texto
with open('./formato_canciones.txt', 'w') as file:
    for song in cleaned_song_list:
        file.write(f"{song}\n")

# Imprimir la lista limpia
cleaned_song_list
