import os
from yt_dlp import YoutubeDL

# Configura la ruta de la unidad USB
usb_drive = "D:"  # Cambia "D:" si tu unidad USB tiene otra letra
name_folder = os.path.join(usb_drive, "Neutro Shorty")

# Crear la carpeta  en la unidad USB si no existe
os.makedirs(name_folder, exist_ok=True)

# Lista de canciones a descargar (solo nombres)
song_list = [
    "Neutro Shorty - 2 Minutos",
    "Neutro Shorty - 3 razones",
    "Neutro Shorty - A Los 16 (",
    "Neutro Shorty - A Lova Weed (Negocio Sucio 2015)",
    "Neutro Shorty - A2P (",
    "Neutro Shorty - Always be",
    "Neutro Shorty - Always Smoking",
    "Neutro Shorty - Amiga",
    "Neutro Shorty - Amor, Odio, Rencor",
    "Neutro Shorty - Aquí Vivo Yo",
    "Neutro Shorty - Asimilalo",
    "Neutro Shorty - Aunque nos Quieran Matar",
    "Neutro Shorty - Ave María (",
    "Neutro Shorty - B.o.b (",
    "Neutro Shorty - Bad Boy",
    "Neutro Shorty - Bang Bang",
    "Neutro Shorty - Barrio solo",
    "Neutro Shorty - Bedroom (19 puntos)",
    "Neutro Shorty - Bendíceme (",
    "Neutro Shorty - Besito De Caramelo",
    "Neutro Shorty - Bien Drogao",
    "Neutro Shorty - Bruja",
    "Neutro Shorty - Buena Mierda",
    "Neutro Shorty - Buscame en otro",
    "Neutro Shorty - BZRP music sessions 21",
    "Neutro Shorty - Camino Solo",
    "Neutro Shorty - Cantante (",
    "Neutro Shorty - Caracas Dream",
    "Neutro Shorty - Caraqueño",
    "Neutro Shorty - Casimiro (",
    "Neutro Shorty - Chica Plastica",
    "Neutro Shorty - Chichar",
    "Neutro Shorty - Cómo Vivimos (",
    "Neutro Shorty - Como Voy a Hacer",
    "Neutro Shorty - Con la muerte",
    "Neutro Shorty - Contacto",
    "Neutro Shorty - Cooking Up (",
    "Neutro Shorty - Costoso",
    "Neutro Shorty - Crema",
    "Neutro Shorty - CSIpher (audio latino) (",
    "Neutro Shorty - Cuídese De La Envidia",
    "Neutro Shorty - Dando la cara (",
    "Neutro Shorty - De Artigas",
    "Neutro Shorty - Dejavu (",
    "Neutro Shorty - Desde Un Bloque",
    "Neutro Shorty - Desnuda son mas brutas",
    "Neutro Shorty - Difamandome",
    "Neutro Shorty - Dime por que",
    "Neutro Shorty - Dinero y Poder",
    "Neutro Shorty - Disfruto (Freestyle)",
    "Neutro Shorty - Drogata",
    "Neutro Shorty - Dulce Caramelo",
    "Neutro Shorty - Easy (",
    "Neutro Shorty - El Coco",
    "Neutro Shorty - El Dios del Sexo (",
    "Neutro Shorty - El Maldito Asesino En Serie",
    "Neutro Shorty - El Mío",
    "Neutro Shorty - El Niño Rapero",
    "Neutro Shorty - El Reloj (",
    "Neutro Shorty - El Robot Del Rap",
    "Neutro Shorty - Ella me dice",
    "Neutro Shorty - En El Banco (",
    "Neutro Shorty - En esta ocasión",
    "Neutro Shorty - Eramos Amigos",
    "Neutro Shorty - Eres Belleza",
    "Neutro Shorty - Es Ella",
    "Neutro Shorty - Estar Sin Ti",
    "Neutro Shorty - Exmusas",
    "Neutro Shorty - Fantasma (",
    "Neutro Shorty - Fantasmas",
    "Neutro Shorty - Farmacéutico",
    "Neutro Shorty - Fashion",
    "Neutro Shorty - Fechoría (",
    "Neutro Shorty - Fémina Venezolana",
    "Neutro Shorty - For My Clicka",
    "Neutro Shorty - Freestyle En FxGorra",
    "Neutro Shorty - Fuck Love",
    "Neutro Shorty - Fulete",
    "Neutro Shorty - G.l.o.c.k",
    "Neutro Shorty - Ganador",
    "Neutro Shorty - Gang Shit",
    "Neutro Shorty - Gelato (",
    "Neutro Shorty - Glock 26",
    "Neutro Shorty - Golden Era",
    "Neutro Shorty - Goodffella",
    "Neutro Shorty - Guetto girl",
    "Neutro Shorty - Hasta Que Salga El Sol",
    "Neutro Shorty - Hope",
    "Neutro Shorty - Hot Gyal",
    "Neutro Shorty - I make this shit",
    "Neutro Shorty - Imaginandote",
    "Neutro Shorty - Inexplicablex",
    "Neutro Shorty - Infidelidad",
    "Neutro Shorty - Infieles",
    "Neutro Shorty - Jeke Flex",
    "Neutro Shorty - Joseando (",
    "Neutro Shorty - Juego (",
    "Neutro Shorty - La ciudad es nostra",
    "Neutro Shorty - La Diferencia",
    "Neutro Shorty - La Fraternidad (El Business) (",
    "Neutro Shorty - La Fraternidad (",
    "Neutro Shorty - La Fraternidad (",
    "Neutro Shorty - La Fraternidad (Intro) (Trap money) (",
    "Neutro Shorty - La Merma",
    "Neutro Shorty - La Movie (",
    "Neutro Shorty - La mujer del P.t.j (",
    "Neutro Shorty - La Original",
    "Neutro Shorty - La Punto 40 (",
    "Neutro Shorty - Las Plagas (",
    "Neutro Shorty - Lastima",
    "Neutro Shorty - Latin Lover (",
    "Neutro Shorty - Lento",
    "Neutro Shorty - Let's Get It",
    "Neutro Shorty - Liomar Masacre",
    "Neutro Shorty - Lo Siento Por Ti",
    "Neutro Shorty - Los Buenos Tiempos",
    "Neutro Shorty - Mala",
    "Neutro Shorty - Malandro",
    "Neutro Shorty - Maquito",
    "Neutro Shorty - María (",
    "Neutro Shorty - Mariwana on the Table",
    "Neutro Shorty - Martirio",
    "Neutro Shorty - Martirio (",
    "Neutro Shorty - Me Compré Un Full (Venezuela Version) (",
    "Neutro Shorty - Meditation",
    "Neutro Shorty - Menu",
    "Neutro Shorty - Mi Chilin",
    "Neutro Shorty - Mi Muñeca",
    "Neutro Shorty - Mi muñeca (",
    "Neutro Shorty - Mi Única Carta",
    "Neutro Shorty - Mil Balas",
    "Neutro Shorty - Mil Semillas",
    "Neutro Shorty - Millones (",
    "Neutro Shorty - Milloneta (",
    "Neutro Shorty - Montuno",
    "Neutro Shorty - Motolita",
    "Neutro Shorty - Mueran las brujas",
    "Neutro Shorty - Muñeca gangster",
    "Neutro Shorty - N4",
    "Neutro Shorty - Nenita mujer",
    "Neutro Shorty - No (",
    "Neutro Shorty - No creo en ninguna",
    "Neutro Shorty - No es mas que otra",
    "Neutro Shorty - No me llames mas",
    "Neutro Shorty - No more love",
    "Neutro Shorty - No sé de ti (",
    "Neutro Shorty - No Voy A Morir Pobre (",
    "Neutro Shorty - Noches en la ciudad",
    "Neutro Shorty - Noches en la platabanda",
    "Neutro Shorty - Obbatala",
    "Neutro Shorty - Obsesión (",
    "Neutro Shorty - Odin",
    "Neutro Shorty - Pasando Duro",
    "Neutro Shorty - Perro",
    "Neutro Shorty - Perro (",
    "Neutro Shorty - Por Siempre",
    "Neutro Shorty - Que No Te Diga Que No",
    "Neutro Shorty - Que Se Sienta (",
    "Neutro Shorty - Que se sienta (",
    "Neutro Shorty - Quien",
    "Neutro Shorty - Reyes",
    "Neutro Shorty - Reyes (",
    "Neutro Shorty - Rey en la calle (",
    "Neutro Shorty - Sabe (",
    "Neutro Shorty - Sabe (",
    "Neutro Shorty - Sangre",
    "Neutro Shorty - Sangre (",
    "Neutro Shorty - Sin Ropa",
    "Neutro Shorty - Sobredosis (",
    "Neutro Shorty - Sonrisas",
    "Neutro Shorty - Soy La Calle",
    "Neutro Shorty - Soy Un Buen Amor (",
    "Neutro Shorty - Te Llevo a la cama (",
    "Neutro Shorty - Tengos Mis Bichos",
    "Neutro Shorty - Tienes Que Venir (",
    "Neutro Shorty - Todo lo que tengo (",
    "Neutro Shorty - Tu cuerpo (",
    "Neutro Shorty - Vamoo (",
    "Neutro Shorty - Venezuela (",
    "Neutro Shorty - Yo Soy La Calle (",
    "Neutro Shorty - Yolo",
]

# Configuración para descargar el audio en el formato original
ydl_opts = {
    'format': 'bestaudio/best',
    'outtmpl': os.path.join(name_folder, '%(title)s - %(uploader)s.%(ext)s'),
    'quiet': False,  # Cambia a True para desactivar la salida en consola
}

# Función para buscar y descargar canciones usando yt_dlp
def download_song(song_name):
    try:
        with YoutubeDL(ydl_opts) as ydl:
            print(f"Buscando y descargando: {song_name}")
            ydl.download([f"ytsearch1:{song_name}"])
            print(f"Descargado: {song_name}")
    except Exception as e:
        print(f"Error al descargar {song_name}: {e}")

# Descargar cada canción en la lista
for song in song_list:
    download_song(song)

print("Descarga completa.")
